import type { Metadata } from "next";
import { Geist, Geist_Mono , Vazirmatn , Noto_Naskh_Arabic, Smooch} from "next/font/google";
import "./globals.css";
 
const vazirFont = Vazirmatn({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={vazirFont.className}
      >
        {children}
      </body>
    </html>
  );
}
